{% set name = "zellij" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

requirements:
  build:
    - {{ compiler('rust') }}

test:
  commands:
    - zellij --help

about:
  home: https://github.com/{{ name }}-org/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A terminal workspace with batteries included 
  description: |
    Zellij is a workspace aimed at developers, ops-oriented people and anyone who loves the terminal. At its core, it is a terminal multiplexer (similar to tmux and screen), but this is merely its infrastructure layer.

  doc_url: https://zellij.dev/
  dev_url: https://github.com/{{ name }}-org/{{ name }}

extra:
  recipe-maintainers:
    - benjaminrwilson

