{% set name = "zellij" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zellij-org/zellij/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6b12ea039462db0c585b17a153acbd2627b8bd41e6f7615e4c2f718ccc4c9b93

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - openssl
    - pkg-config

test:
  commands:
    - zellij --help

about:
  home: https://github.com/{{ name }}-org/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A terminal workspace with batteries included 
  description: |
    Zellij is a workspace aimed at developers, ops-oriented people and anyone who loves the terminal. At its core, it is a terminal multiplexer (similar to tmux and screen), but this is merely its infrastructure layer.

  doc_url: https://zellij.dev/
  dev_url: https://github.com/{{ name }}-org/{{ name }}

extra:
  recipe-maintainers:
    - benjaminrwilson
